// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkkcbquonvdkhhmopbgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhra2NicXVvbnZka2hobW9wYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDYzNDksImV4cCI6MjA2OTk4MjM0OX0.k7I1BwjW3MjDgC0rOkWSKEyLv81gw7F_nWWtjMs1WPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});